In [2]:
import sys

sys.path.append('/home/czl/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# eval with dataset
locagent_loc_file = 'loc_output/locagent/claude_3-5/loc_outputs.jsonl'
locagent_res = evaluate_results(locagent_loc_file,
                                level2key_dict,
                                metrics=['acc'],  # 使用准确率(accuracy)作为评估指标
                                # metrics=['ndcg'], # 备选指标：归一化折损累积增益
                                )
locagent_res

     file                 module         function
    Acc@1   Acc@3   Acc@5  Acc@5  Acc@10    Acc@5  Acc@10
0  0.7774  0.9197  0.9416  0.865  0.8759   0.7336  0.7737

In [3]:
from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# eval with dataset
locagent_loc_file = '../results/location/merged_loc_outputs_mrr.jsonl'
locagent_res = evaluate_results(locagent_loc_file,
                                level2key_dict,
                                dataset="czlll/Loc-Bench_V1",
                                metrics=['acc'],  # 使用准确率(accuracy)作为评估指标
                                # metrics=['ndcg'], # 备选指标：归一化折损累积增益
                                selected_list=['UXARRAY__uxarray-1117']
                                )
locagent_res

   file             module        function
  Acc@1 Acc@3 Acc@5  Acc@5 Acc@10    Acc@5 Acc@10
0   1.0   0.0   0.0    0.0    0.0      0.0    0.0

In [1]:
from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# eval with dataset
locagent_loc_file = '../results/product_tree_data_cleaning/merged_loc_outputs_mrr.jsonl'
local_dataset_file = '../dataset/product_tree_data_cleaning.json'
locagent_res = evaluate_results(locagent_loc_file,
                                level2key_dict,
                                local_dataset_file,
                                metrics=['acc'],  # 使用准确率(accuracy)作为评估指标
                                # metrics=['ndcg'], # 备选指标：归一化折损累积增益
                                )
locagent_res

   file             module        function
  Acc@1 Acc@3 Acc@5  Acc@5 Acc@10    Acc@5 Acc@10
0   1.0   1.0   1.0    1.0    1.0      1.0    1.0